language: python

python:
  - "2.7"
  - "3.4"

notifications:
  email:
    on_success: never
    on_failure: always

install:
  - pip install -r requirements.txt
  - pip install flake8 pylint

script:
 - ./.pre-commit
